export const mainURL = 'https://via.crmdemo.co.in';
export const baseURL = mainURL + '/VIAApp_Services.svc/';
export const imageURL = mainURL + '/Admin';
export const presidentImageURL = imageURL + '/President/2.jpeg';
export const eventImageURL = imageURL + '/Event/EventImg/';
export const newsImageURL = imageURL + '/News/NewsImg/';
export const officeBearersImageURL = imageURL + '/MemberPhoto/';
export const pastPresidentImageURL = imageURL + '/PastPresidentPhoto/';
export const meetingsImageURL = mainURL + '/AndroidImages/Meetings/';
export const departmentIcon = mainURL + '/AndroidImages/Departments/';
export const committeeIcon = mainURL + '/AndroidImages/committee/';

export const GET_ADVERTISEMENT_REQUEST = 'GET_ADVERTISEMENT_REQUEST';
export const GET_ADVERTISEMENT_SUCCESS = 'GET_ADVERTISEMENT_SUCCESS';
export const GET_ADVERTISEMENT_ERROR = 'GET_ADVERTISEMENT_ERROR';

export const GET_EVENTS_REQUEST = 'GET_EVENTS_REQUEST';
export const GET_EVENTS_SUCCESS = 'GET_EVENTS_SUCCESS';
export const GET_EVENTS_ERROR = 'GET_EVENTS_ERROR';

export const GET_EVENTS_DETAILS_REQUEST = 'GET_EVENTS_DETAILS_REQUEST';
export const GET_EVENTS_DETAILS_SUCCESS = 'GET_EVENTS_DETAILS_SUCCESS';
export const GET_EVENTS_DETAILS_ERROR = 'GET_EVENTS_DETAILS_ERROR';

export const GET_NEWS_REQUEST = 'GET_NEWS_REQUEST';
export const GET_NEWS_SUCCESS = 'GET_NEWS_SUCCESS';
export const GET_NEWS_ERROR = 'GET_NEWS_ERROR';

export const GET_NEWS_DETAILS_REQUEST = 'GET_NEWS_DETAILS_REQUEST';
export const GET_NEWS_DETAILS_SUCCESS = 'GET_NEWS_DETAILS_SUCCESS';
export const GET_NEWS_DETAILS_ERROR = 'GET_NEWS_DETAILS_ERROR';

export const GET_OFFICE_BEARERS_REQUEST = 'GET_OFFICE_BEARERS_REQUEST';
export const GET_OFFICE_BEARERS_SUCCESS = 'GET_OFFICE_BEARERS_SUCCESS';
export const GET_OFFICE_BEARERS_ERROR = 'GET_OFFICE_BEARERS_ERROR';

export const GET_ELECTED_MEMBERS_REQUEST = 'GET_ELECTED_MEMBERS_REQUEST';
export const GET_ELECTED_MEMBERS_SUCCESS = 'GET_ELECTED_MEMBERS_SUCCESS';
export const GET_ELECTED_MEMBERS_ERROR = 'GET_ELECTED_MEMBERS_ERROR';

export const GET_INVITE_MEMBERS_REQUEST = 'GET_INVITE_MEMBERS_REQUEST';
export const GET_INVITE_MEMBERS_SUCCESS = 'GET_INVITE_MEMBERS_SUCCESS';
export const GET_INVITE_MEMBERS_ERROR = 'GET_INVITE_MEMBERS_ERROR';

export const GET_PAST_PRESIDENTS_REQUEST = 'GET_PAST_PRESIDENTS_REQUEST';
export const GET_PAST_PRESIDENTS_SUCCESS = 'GET_PAST_PRESIDENTS_SUCCESS';
export const GET_PAST_PRESIDENTS_ERROR = 'GET_PAST_PRESIDENTS_ERROR';

export const GET_ASSETS_DETAIL_REQUEST = 'GET_ASSETS_DETAIL_REQUEST';
export const GET_ASSETS_DETAIL_SUCCESS = 'GET_ASSETS_DETAIL_SUCCESS';
export const GET_ASSETS_DETAIL_ERROR = 'GET_ASSETS_DETAIL_ERROR';

export const GET_SPORTS_GAMES_REQUEST = 'GET_SPORTS_GAMES_REQUEST';
export const GET_SPORTS_GAMES_SUCCESS = 'GET_SPORTS_GAMES_SUCCESS';
export const GET_SPORTS_GAMES_ERROR = 'GET_SPORTS_GAMES_ERROR';

export const GET_INDUSTRIAL_REQUEST = 'GET_INDUSTRIAL_REQUEST';
export const GET_INDUSTRIAL_SUCCESS = 'GET_INDUSTRIAL_SUCCESS';
export const GET_INDUSTRIAL_ERROR = 'GET_INDUSTRIAL_ERROR';

export const GET_DEPARTMENT_REQUEST = 'GET_DEPARTMENT_REQUEST';
export const GET_DEPARTMENT_SUCCESS = 'GET_DEPARTMENT_SUCCESS';
export const GET_DEPARTMENT_ERROR = 'GET_DEPARTMENT_ERROR';

export const GET_GOV_CONTACTS_REQUEST = 'GET_GOV_CONTACTS_REQUEST';
export const GET_GOV_CONTACTS_SUCCESS = 'GET_GOV_CONTACTS_SUCCESS';
export const GET_GOV_CONTACTS_ERROR = 'GET_GOV_CONTACTS_ERROR';

export const GET_MEETINGS_REQUEST = 'GET_MEETINGS_REQUEST';
export const GET_MEETINGS_SUCCESS = 'GET_MEETINGS_SUCCESS';
export const GET_MEETINGS_ERROR = 'GET_MEETINGS_ERROR';

export const GET_MEETINGS_DETAILS_REQUEST = 'GET_MEETINGS_DETAILS_REQUEST';
export const GET_MEETINGS_DETAILS_SUCCESS = 'GET_MEETINGS_DETAILS_SUCCESS';
export const GET_MEETINGS_DETAILS_ERROR = 'GET_MEETINGS_DETAILS_ERROR';

export const GET_EMERGENCY_CONTACTS_REQUEST = 'GET_EMERGENCY_CONTACTS_REQUEST';
export const GET_EMERGENCY_CONTACTS_SUCCESS = 'GET_EMERGENCY_CONTACTS_SUCCESS';
export const GET_EMERGENCY_CONTACTS_ERROR = 'GET_EMERGENCY_CONTACTS_ERROR';

export const GET_EXPERT_PANEL_REQUEST = 'GET_EXPERT_PANEL_REQUEST';
export const GET_EXPERT_PANEL_SUCCESS = 'GET_EXPERT_PANEL_SUCCESS';
export const GET_EXPERT_PANEL_ERROR = 'GET_EXPERT_PANEL_ERROR';

export const GET_DIRECTORS_VGEL_REQUEST = 'GET_DIRECTORS_VGEL_REQUEST';
export const GET_DIRECTORS_VGEL_SUCCESS = 'GET_DIRECTORS_VGEL_SUCCESS';
export const GET_DIRECTORS_VGEL_ERROR = 'GET_DIRECTORS_VGEL_ERROR';

export const GET_MESSAGES_REQUEST = 'GET_MESSAGES_REQUEST';
export const GET_MESSAGES_SUCCESS = 'GET_MESSAGES_SUCCESS';
export const GET_MESSAGES_ERROR = 'GET_MESSAGES_ERROR';

export const GET_MESSAGES_DETAILS_REQUEST = 'GET_MESSAGES_DETAILS_REQUEST';
export const GET_MESSAGES_DETAILS_SUCCESS = 'GET_MESSAGES_DETAILS_SUCCESS';
export const GET_MESSAGES_DETAILS_ERROR = 'GET_MESSAGES_DETAILS_ERROR';

export const GET_COMMITTE_REQUEST = 'GET_COMMITTE_REQUEST';
export const GET_COMMITTE_SUCCESS = 'GET_COMMITTE_SUCCESS';
export const GET_COMMITTE_ERROR = 'GET_COMMITTE_ERROR';

export const GET_COMMITTE_DETAILS_REQUEST = 'GET_COMMITTE_DETAILS_REQUEST';
export const GET_COMMITTE_DETAILS_SUCCESS = 'GET_COMMITTE_DETAILS_SUCCESS';
export const GET_COMMITTE_DETAILS_ERROR = 'GET_COMMITTE_DETAILS_ERROR';

export const CREATE_FEEDBACK_REQUEST = 'CREATE_FEEDBACK_REQUEST';
export const CREATE_FEEDBACK_SUCCESS = 'CREATE_FEEDBACK_SUCCESS';
export const CREATE_FEEDBACK_ERROR = 'CREATE_FEEDBACK_ERROR';

export const GET_DEPARTMENT_DETAIL_REQUEST = 'GET_DEPARTMENT_DETAIL_REQUEST';
export const GET_DEPARTMENT_DETAIL_SUCCESS = 'GET_DEPARTMENT_DETAIL_SUCCESS';
export const GET_DEPARTMENT_DETAIL_ERROR = 'GET_DEPARTMENT_DETAIL_ERROR';

export const GET_WELCOME_MESSAGE_REQUEST = 'GET_WELCOME_MESSAGE_REQUEST';
export const GET_WELCOME_MESSAGE_SUCCESS = 'GET_WELCOME_MESSAGE_SUCCESS';
export const GET_WELCOME_MESSAGE_ERROR = 'GET_WELCOME_MESSAGE_ERROR';
